name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-algorithms:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Algorithms
      run: dotnet restore
    - name: Build
      working-directory: ./Algorithms
      run: dotnet build --no-restore
    - name: Test with dotnet
      working-directory: ./Algorithms
      run: dotnet test --logger trx --results-directory "TestResults-Algorithms"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-algorithms-tests
        path: ./Algorithms/TestResults-Algorithms
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: dotnet-results-algorithms-tests
        path: ./Algorithms/TestResults-Algorithms
        
  test-data-structures:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./DataStructures
      run: dotnet restore
    - name: Build
      working-directory: ./DataStructures
      run: dotnet build --no-restore
    - name: Test with dotnet
      working-directory: ./DataStructures
      run: dotnet test --logger trx --results-directory "TestResults-DataStructures"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-data-structures-tests
        path: ./DataStructures/TestResults-DataStructures
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: dotnet-results-data-structures-tests
        path: ./DataStructures/TestResults-DataStructures

