name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-algorithms:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Algorithms
      run: dotnet restore
    - name: Build
      working-directory: ./Algorithms
      run: dotnet build --no-restore
    - name: Test with dotnet
      working-directory: ./Algorithms
      run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: ./Algorithms/TestResults-${{ matrix.dotnet-version }}
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: ./Algorithms/TestResults-${{ matrix.dotnet-version }}

