name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-algorithms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run:
        cd "Algorithms"
        dotnet restore
    - name: Build
      run: 
        cd "Algorithms"
        dotnet build --no-restore
  test-algorithms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: 
        cd "Algorithms"
        dotnet restore
    - name: Build
      run: 
        cd "Algorithms"
        dotnet test
  
