name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-algorithms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Open Directory of Server
      run: cd ".\Algorithms\HackerRank.Algorithms"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  test-algorithms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Open Directory of Server
      run: cd ".\Algorithms\HackerRank.Algorithms.Tests"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet test
  
